# config/mission_config.yaml
mission:
  name: "ISS Docking Scenario"
  duration: 1800  # seconds
  num_agents: 3
  
spacecraft:
  initial_mass: 500  # kg
  inertia_matrix: [[100, 0, 0], [0, 100, 0], [0, 0, 150]]
  
  thrusters:
    max_thrust: 10  # N
    max_torque: 1   # Nm
    specific_impulse: 300  # s
  
  sensors:
    position_noise: 0.1  # m
    velocity_noise: 0.01  # m/s
    attitude_noise: 0.001  # rad

dr_mpc:
  prediction_horizon: 20
  time_step: 0.1  # s
  wasserstein_radius: 0.1
  confidence_level: 0.95
  
coordination:
  communication_delay: 0.1  # s
  safety_radius: 5.0  # m
  consensus_tolerance: 1e-3

environment:
  orbital_altitude: 400000  # m
  orbital_rate: 0.0011  # rad/s
  
disturbances:
  j2_perturbation: true
  solar_radiation_pressure: true
  atmospheric_drag: false  # Negligible at 400km