# config/advanced_system_config.yaml
advanced_features:
  machine_learning:
    enabled: true
    model_path: "models/uncertainty_predictor.pt"
    update_interval: 10  # seconds
    learning_rate: 0.001
    
  formation_flying:
    enabled: true
    formation_types: ["line", "triangle", "circle", "v_shape"]
    inter_spacecraft_distance: 10.0  # meters
    reconfiguration_time: 30.0  # seconds
    
  fault_tolerance:
    enabled: true
    num_thrusters: 12
    redundancy_level: 2
    monitoring_rate: 10  # Hz
    fault_threshold: 0.1
    
  security:
    enabled: true
    encryption_algorithm: "AES-256"
    key_rotation_interval: 3600  # seconds
    signature_algorithm: "RSA-2048"
    
integration:
  mission_phases:
    - formation_approach
    - precision_docking
    - formation_keeping
    - fault_recovery
    
  real_time_requirements:
    ml_inference_time: <5ms
    formation_update_rate: 10Hz
    fault_detection_time: <100ms
    encryption_overhead: <1ms