title: Multi-Agent Spacecraft Docking System
description: Distributionally Robust Model Predictive Control for Autonomous Spacecraft Operations
url: "https://abhishek282001tiwari.github.io"
baseurl: "/Multi-Agent_Path_Planning_for_Spacecraft_Docking_Using_Distributional_Robust_MPC"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  docs:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "page"
