# .github/workflows/ci.yml
mkdir -p .github/workflows
cat > .github/workflows/ci.yml << 'EOF'
name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/ --cov=src --cov-report=html
    - name: Build Docker
      run: |
        docker build -t spacecraft-drmpc .
    - name: Deploy to staging
      if: github.ref == 'refs/heads/main'
      run: |
        echo "🚀 Deploying to production..."
EOF
